with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  github.com/iFreezy/catalog-service/internal/app/repository:
    interfaces:
      Product:
      Category:
